// Auto-generated by pcc from `main.p`
#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int main() {
    double pi, e;
    int n;
    
    while ( pi == 3.14 && e == 2.72 ) {
        e = e + 1;
        pi = pi - 1;
    }

	return 0;
}