// Auto-generated by pcc from `main.p`
#include <iostream>
using namespace std;

int main() {
    double pi, e;
    int n;
    
    cin >> n;
    
    while ( pi == 3.14 && e == 2.72 ) {
        e = e + 1;
        pi = pi - 1;
    }
    
    cout << e << pi << endl;
    cout << n << endl;

	return 0;
}